name: blog pribadi
description: Web, Programming dan Linux
meta_description: "Linux, Web Development, #XC"

aboutPage: true

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'https://harry.yunanto.net'
# google_analytics: 'UA-XXXXXXXX-X'
# disqus: false
# disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'https://harry.yunanto.net'
author:         'Harry Yunanto'
authorTwitter:  'iorme'

permalink:       /:year/:month/:title

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
